version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=@P@ssw0rd02
    volumes:
      - ../data/db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
